version: "3.8"

volumes:
  volume-kibana:
  volume-elastic:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-latest}
    profiles:
      - logging-elk
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - volume-elastic:/usr/share/elasticsearch/data
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-latest}
    profiles:
      - logging-elk
    ports: ["5601:5601"]
    restart: on-failure
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - volume-kibana:/usr/share/kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  #  docker run -d \
  #  --name=filebeat \
  #  --user=root \
  #  --volume="$(pwd)/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro" \
  #  --volume="/var/lib/docker/containers:/var/lib/docker/containers:ro" \
  #  --volume="/var/run/docker.sock:/var/run/docker.sock:ro" \
  #  docker.elastic.co/beats/filebeat:7.10.2 filebeat -e -strict.perms=false \
  #  -E output.elasticsearch.hosts=["elasticsearch:9200"]
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION:-latest}
    command: filebeat -e -strict.perms=false
    profiles:
      - logging-elk
    volumes:
      - ./data-filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro  # Configuration file
      -  /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      -  /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root
    restart: on-failure
    networks:
      - ${GLOBAL_NETWORK:-elastic}



