version: "3.8"
services:
  mongo:
    image: mongo:${MONGO_VERSION:-latest}
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./data-mongo:/docker-entrypoint-initdb.d
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - ${GLOBAL_NETWORK:-elastic}

