version: "3.8"
services:
  mongo:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        MONGO_VERSION: ${MONGO_VERSION:-latest}
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - ${GLOBAL_NETWORK:-elastic}

