version: "3.8"
services:
  job-service:
    build:
      context: ../../job-service
      dockerfile: Dockerfile
    image: ${GROUP_ID:-artarkatesoft}/art-vinsguru-job-service:${SERVICE_VERSION:-latest}
    environment:
      "spring.data.mongodb.host": mongo
    ports:
      - "8090:8090"
    depends_on:
      - mongo
    networks:
      - ${GLOBAL_NETWORK:-services}
