version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin-slim:${ZIPKIN_VERSION:-latest}
    profiles:
      - tracing
    ports: [ "9411:9411" ]
    networks:
      - ${GLOBAL_NETWORK:-elastic}
