version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin-slim:${ZIPKIN_VERSION:-latest}
    profiles:
      - tracing
    ports: [ "9411:9411" ]
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: http://elasticsearch:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}
