server:
  port: 8091

spring:
  data:
    mongodb:
#      uri: mongodb://candidate_user:candidate_password@localhost:27017/candidate_db #this format has a lot of options
      host: localhost
      port: 27017
      username: candidate_user
      password: candidate_password
      database: candidate_db

app.job-service.base-url: http://localhost:8090

---
spring:
  config:
    activate:
      on-profile: mockserver
app.job-service.base-url: http://localhost:1080
