version: "3.0"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: art
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: product_db
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres:5432