FROM openjdk:11-jre-slim as builder

WORKDIR /usr/share/app

COPY target/*.jar app.jar

RUN java -Djarmode=layertools -jar app.jar extract

FROM openjdk:11-jre-slim

WORKDIR /usr/share/app
COPY --from=builder /usr/share/app/dependencies/ ./
COPY --from=builder /usr/share/app/spring-boot-loader/ ./
COPY --from=builder /usr/share/app/snapshot-dependencies/ ./
COPY --from=builder /usr/share/app/application/ ./
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "org.springframework.boot.loader.JarLauncher"]
